# spin/codegen.rb — expand a resource table into compilable ruby.
#
# input:  a Spin::DSL (resources, each with read/write block source).
# output: a string of spinel-compilable ruby — `read`/`write` methods whose
#         bodies are `case resource(req) … end`, with each resource's block
#         body spliced in as a branch, plus `require_relative "spin"` and a
#         trailing `spin_run`.
#
# the emitted shape is exactly what we verified compiles:
#
#   require_relative "spin"
#   def read(req)
#     case resource(req)
#     when "notes" then
#       <block body>
#     else
#       reply(404, "no such resource: #{req["path"]}")
#     end
#   end
#   def write(req) … end
#   spin_run

require_relative 'dsl'

module Spin
  module Codegen
    module_function

    # generate the handler source for a loaded DSL.
    # `prelude_path` is how the generated file will `require_relative` spin.rb
    # (relative to where the generated file is written).
    def generate(dsl, prelude_path: 'spin')
      out = +""
      out << "# generated by `spin build` — do not edit.\n"
      out << "# edit the source .rb (the resource DSL) and rebuild.\n\n"
      out << "require_relative #{prelude_path.inspect}\n\n"

      out << method_for('read', dsl) { |r| r.read_block }
      out << "\n"
      out << method_for('write', dsl) { |r| r.write_block }
      out << "\n"
      out << "spin_run\n"
      out
    end

    # build a `def read(req) … end` (or write) from the resources that have a
    # block for this verb. resources lacking the verb simply aren't branches —
    # so a resource with no `write` is read-only, and the else-branch 405s.
    def method_for(verb, dsl)
      branches = dsl.resources.filter_map do |r|
        block = yield(r)
        next unless block
        body = BlockSource.for(block)
        raise DSL::Error, "could not extract #{verb} block for resource #{r.name.inspect}" if body.nil?
        [r.name, body.strip]
      end

      io = +"def #{verb}(req)\n"
      io << "  case resource(req)\n"
      branches.each do |name, body|
        io << "  when #{name.inspect} then\n"
        body.each_line { |ln| io << "    #{ln.rstrip}\n" }
      end
      io << "  else\n"
      io << "    #{default_else(verb)}\n"
      io << "  end\n"
      io << "end\n"
      io
    end

    def default_else(verb)
      if verb == 'read'
        %{reply(404, "no such resource: \#{req["path"]}")}
      else
        %{reply(405, "\#{resource(req)} is read-only")}
      end
    end
  end
end
